server:
    port: 9061

spring:
    application:
                  name: sharding-jdbc-split
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    order0_master:
                    type: com.alibaba.druid.pool.DruidDataSource
                    driver-class-name: com.mysql.jdbc.Driver
                    url: jdbc:mysql://localhost:3306/order_0?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
                    username: root
                    password:
                    initial-size: 5
                    min-idle: 1
                    max-active: 5
                    max-wait: 60000
                    time-between-eviction-runs-millis: 60000
                    min-evictable-idle-time-millis: 30000
                    max-evictable-idle-time-millis: 60000
    order0_slave_0:
                    type: com.alibaba.druid.pool.DruidDataSource
                    driver-class-name: com.mysql.jdbc.Driver
                    url: jdbc:mysql://localhost:3306/order_0?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
                    username: root
                    password:
                    initial-size: 5
                    min-idle: 1
                    max-active: 5
                    max-wait: 60000
                    time-between-eviction-runs-millis: 60000
                    min-evictable-idle-time-millis: 30000
                    max-evictable-idle-time-millis: 60000
    order0_slave_1:
                    type: com.alibaba.druid.pool.DruidDataSource
                    driver-class-name: com.mysql.jdbc.Driver
                    url: jdbc:mysql://localhost:3306/order_0?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
                    username: root
                    password:
                    initial-size: 5
                    min-idle: 1
                    max-active: 5
                    max-wait: 60000
                    time-between-eviction-runs-millis: 60000
                    min-evictable-idle-time-millis: 30000
                    max-evictable-idle-time-millis: 60000

    order1_master:
                    type: com.alibaba.druid.pool.DruidDataSource
                    driver-class-name: com.mysql.jdbc.Driver
                    url: jdbc:mysql://localhost:3306/order_1?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
                    username: root
                    password:
                    initial-size: 5
                    min-idle: 1
                    max-active: 5
                    max-wait: 60000
                    time-between-eviction-runs-millis: 60000
                    min-evictable-idle-time-millis: 30000
                    max-evictable-idle-time-millis: 60000
    order1_slave_0:
                    type: com.alibaba.druid.pool.DruidDataSource
                    driver-class-name: com.mysql.jdbc.Driver
                    url: jdbc:mysql://localhost:3306/order_1?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
                    username: root
                    password:
                    initial-size: 5
                    min-idle: 1
                    max-active: 5
                    max-wait: 60000
                    time-between-eviction-runs-millis: 60000
                    min-evictable-idle-time-millis: 30000
                    max-evictable-idle-time-millis: 60000
    order1_slave_1:
                    type: com.alibaba.druid.pool.DruidDataSource
                    driver-class-name: com.mysql.jdbc.Driver
                    url: jdbc:mysql://localhost:3306/order_1?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
                    username: root
                    password:
                    initial-size: 5
                    min-idle: 1
                    max-active: 5
                    max-wait: 60000
                    time-between-eviction-runs-millis: 60000
                    min-evictable-idle-time-millis: 30000
                    max-evictable-idle-time-millis: 60000
    datasource:
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.jdbc.Driver
                url: jdbc:mysql://localhost:3306/order_0?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
                username: root
                password:
                initial-size: 5
                min-idle: 1
                max-active: 5
                max-wait: 60000
                time-between-eviction-runs-millis: 60000
                min-evictable-idle-time-millis: 30000
                max-evictable-idle-time-millis: 60000




logging:
        org:
            springframework: WARN
            spring:
                    springboot:
                                dao: DEBUG
        level:
#              ROOT: DEBUG
              com:
                  abin:
                        lee:
                            sharding:
                                      jdbc:
                                            dao:
                                                 DEBUG
#                                                 OrderMapper: DEBUG
#                                                 OrderItemMapper: DEBUG

swagger:
          show: true


#本地开发联调标识
#local:
#      dev:
#          flag: true
